version: '3'
services:
  apache:
    build: .docker/apache
    container_name: sf4_apache
    ports:
      - 80:80
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - web-site-volume:/home/wwwroot/sf4
    depends_on:
      - php

  mysql:
    image: mysql
    container_name: sf4_mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4

  php:
    build: .docker/php
    container_name: sf4_php
    volumes:
      - web-site-volume:/home/wwwroot/sf4
    environment:
      - maildev_host=sf4_maildev
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    links:
      - mysql:db
    ports:
      - 8080:80
    depends_on:
      - mysql

volumes:
  web-site-volume:
  mysql-volume: