version: '3'
services:
  apache:
    build: ./apache
    container_name: sf4_apache
    ports:
      - 80:80
    volumes:
      - ./src:/home/wwwroot/sf4
      - ./apache/vhosts:/etc/apache2/sites-enabled
      - ./apache/install.sh:/usr/local/bin/install.sh
      - ./apache/entrypoint.sh:/usr/local/bin/custom-entrypoint
    working_dir: /home/wwwroot/sf4
    environment:
      # pass .env variables to the container
      HOST_USER_ID: ${HOST_USER_ID:-1000}
      HOST_GROUP_ID: ${HOST_GROUP_ID:1000}
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:8.0
    container_name: sf4_mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    command: ["mysqld", "--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sf4
      MYSQL_USER: sf4
      MYSQL_PASSWORD: sf4
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sf4_phpmyadmin
    # add some environment variable to the container
    # in order to be able to connect to mysql server
    # see https://hub.docker.com/r/phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    ports:
      - 8080:80
    depends_on:
      - mysql
    networks:
      - frontend
      - backend

volumes:
  mysql-volume:

networks:
  frontend:
  backend: