version: "3"

services:
  client:
    build: ./.docker/client
    container_name: node
    volumes:
      - ./src/client:/data
      - node-modules:/data/node_modules
      - ./.docker/client/entrypoint.sh:/entrypoint/entrypoint.sh
    command: ['sleep', '999d']
    networks:
      - app-network

  server:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "${HOST_SERVER_PORT:-80}:80"
    volumes:
      - ./src/client:/data
      - ./.docker/server/etc/conf.d/:/etc/nginx/conf.d/

    #command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - client
    networks:
      - app-network

networks:
  app-network:

volumes:
  node-modules: